import { sidebar } from "vuepress-theme-hope";

// 精选图标：https://theme-hope.vuejs.press/zh/guide/interface/icon.html#iconfont-%E7%B2%BE%E9%80%89%E5%9B%BE%E6%A0%87
export default sidebar([
  // 指定显示页面
  {
    text: "🧰 算法笔记",
    icon: "",
    prefix: "/leetcode/",
    link: "",
    collapsible: true,
    children: [
      {
        text: "基础",
        icon: "check",
        prefix: "a-base/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "排序",
        icon: "check",
        prefix: "sort/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "数组",
        icon: "check",
        prefix: "array/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "链表",
        icon: "check",
        prefix: "list/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "栈与队列",
        icon: "check",
        prefix: "stack/",
        link: "",
        collapsible: true,
        children: "structure",
      },

      {
        text: "字符串",
        icon: "check",
        prefix: "string/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "哈希表",
        icon: "check",
        prefix: "hash/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "位运算",
        icon: "check",
        prefix: "bit/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "图论",
        icon: "check",
        prefix: "graph/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "树",
        icon: "check",
        prefix: "tree/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "并查集",
        icon: "check",
        prefix: "unionfind/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "回溯",
        icon: "check",
        prefix: "backtracking/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "贪心",
        icon: "check",
        prefix: "greedy/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "前缀和与差分",
        icon: "check",
        prefix: "prefix/",
        link: "",
        collapsible: true,
        children: "structure",
      },
      {
        text: "动态规划",
        icon: "check",
        prefix: "dp/",
        link: "",
        collapsible: true,
        children: "structure",
      },
    ],
  },
]);
